name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "fzmlp3aplmijjhvxwbbdzqzt"
  title = "review filemanager"
  description = "<p>stop point on groupfileview</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "u3svfseyzcw92fcjj1xe5t13"
    title = "translation key"
    completed = false

    [[processes.tasks.checkList]]
    id = "cgf4yvntr5ra7mvsqfxxey13"
    title = "seperate code"
    completed = false

    [[processes.tasks.checkList]]
    id = "gccrqmc6w8v2txyzy1q7kv07"
    title = ""
    completed = false

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
